name: Deploy My Project

on:
  push:
    branches:
      - master # trigger branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # use the latest

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22 # for vite.js

      - name: Install dependencies
        run: yarn install --frozen-lockfile # I prefer yarn

      - name: Build
        run: |
          yarn build
          yarn build:demo

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # change it if you like
